### PR TITLE
Update symfony/finder version for compatibility with Symfony 3

### LINKED ISSUE #15: Issue with Symfony 3
Hi,

Refer: https://github.com/irazasyed/laravel-gamp/issues/10

This can be resolve if you update your composer to add support to 3.0:

```json
"symfony/finder": "^2.5|^3.0"
```

But I'm not sure what has been changed, So you'll need to check that and update it accordingly. If you don't, then people will not be able to use this with Laravel 5.2 which is the last stable version. 

Please do look into it and update.

### PR DESCRIPTION
**Pull request by Fedott**
Fixes #15

### CODE REVIEW

**Comment by Fedott** [comment]
Hi!
What do I need to merge this request?

**Comment by venyii** [comment]
@jorgeborges Any chance to get this merged?

**Comment by mbardelmeijer** [comment]
@jorgeborges *poke*

**Comment by jorgeborges** [comment]
@Fedott @venyii @mbardelmeijer Sorry for taking so long for reviewing/merging this, folks. We've been very busy with other projects.

I'll be reviewing it and merging this weekend.

**Comment by venyii** [comment]
Thank you!

**Comment by jorgeborges** [comment]
@Fedott @venyii @mbardelmeijer I removed the dependency altogether in the latest release. You guys should have no issues now.

Update to the latest version (should be automatic in your deployment pipeline if you used "^2.0" in Composer)

**Pull request closed without merging**
