### PR TITLE
Migration to Guzzle 6.0

### PR DESCRIPTION
**Pull request by baibaratsky**

### CODE REVIEW

**Comment by baibaratsky** [comment]
Unfortunately, PHP 5.4 is not supported by new Guzzle.

**Comment by jorgeborges** [comment]
Hi @baibaratsky,

The problem is that we internally still use PHP 5.4 (the plan is to update at the end of the year to PHP 7).

However, what I'll do is code review your pull request and if everything is OK I'll merge and release a v2.0 for the library because of breaking changes. Then we'll have to maintain the v1 and v2 branch separately, but should be easy since this library is pretty much done.

**Comment by baibaratsky** [comment]
Ok. I’m looking forward.

**Comment by jorgeborges** [comment]
@baibaratsky  Its merged now, thanks!

**Pull request merged**
