### PR TITLE
Support to run in debug mode so that we can validate hits.

### PR DESCRIPTION
**Pull request by amit0rana**
Enables us to validate hits.

### CODE REVIEW

**Comment by spryka** [comment]
please release this feature

**Comment by GinoPane** [comment]
It is better to fix the branch in order to be built successful.

**Comment by Nightbr** [comment]
hi, it could be a really nice feature!
@amit0rana can you fixed the branch in order to pass all build tests and merge this amazing feature!

Thanks!!

**Comment by jorgeborges** [comment]
Sorry for taking so long for reviewing/merging this, folks. We've been very busy with other projects.

I'll be reviewing it and merging this weekend.

**Pull request merged**
